### ISSUE TITLE
How to use this in Node.js app?

### ISSUE THREAD

**Issue by rwaldron** [surfinzap/typopo#19]
```js
const typopo = require('typopo');
console.log(typopo);
```

This logs an empty object.

**Comment by surfinzap** [comment]
Hi @rwaldron, thanks for reaching out! I'm trying to make it work in node.js app, but since I'm not so experienced with module packaging for Node.js, it's more of trial/error at my side. 

Here's how @krasi0 found a workaround, you can try it if it helps → https://github.com/surfinzap/typopo/issues/12

**Comment by surfinzap** [comment]
Hi @rwaldron, since [version 2.3.1](https://github.com/surfinzap/typopo/releases/tag/2%2F3%2F1) you can now use typopo as a part of a Node.js project. Let me know, when you ran into any issues.
